# Copyright (c) 2019 Lightricks. All rights reserved.
# Created by Noam Freeman.

import collections
from enum import Enum

import MarkdownUtils

COMMENT_HEADER = """
## Lightricks CI status
    
<table>
"""

COMMENT_FOOTER = """
</table>
    
<p align="right">
Generated by the Lightricks android jenkins team :hammer:
</p>
"""

def report_markdown(entries):
    modules = collections.defaultdict(list)
    for entry in entries:
        modules[entry.module].append(entry)

    table = \
        '\n'.join(_report_module(module.capitalize(), modules[module]) for module in modules.keys())
    return COMMENT_HEADER + table + COMMENT_FOOTER

class Status(Enum):
    OK = "OK"
    WARNING = "WARNING"
    ERROR = "ERROR"

    def emoji(self):
        return {Status.OK: ":white_check_mark:",
                Status.WARNING: ":warning:",
                Status.ERROR: ":x:"}[self]

ReportEntry = collections.namedtuple("ReportEntry", 'module status stage info details')

def _report_entry_markdown(entry):
    details_markdown = f"{ MarkdownUtils.details_tag('Details', entry.details) }" if entry.details else ""
    return f" {entry.status.emoji()} {entry.stage}: {entry.info}<br/>{details_markdown}"

def _report_module(module_caption, module_entries):
    module_report = ''.join(_report_entry_markdown(entry) for entry in module_entries)
    return f"<tr><td><b> {module_caption} </b></td><td> {module_report} </td></tr>\n"
