def get_key_dict():
    return {
        "app_name": None,
        "loading": "Loading...",
        "exporting": None,
        "restoring": "Restoring...",
        "reloading": "Reloading...",
        "processing": "Processing...",
        "feature_reshape": "0Pv-Xv-10t.normalTitle",
        "feature_whiten": "Txj-oa-3f4.normalTitle",
        "feature_details": "flG-IP-GGm.normalTitle",
        "feature_smooth": "odO-E6-xJG.normalTitle",
        "feature_defocus": "Ndg-PW-N2Y.normalTitle",
        "feature_patch": "he7-Bv-eRu.normalTitle",
        "feature_frames": "lLH-gs-BDd.normalTitle",
        "feature_tones": "FKL-z0-cSr.normalTitle",
        "feature_filters": "EtJ-EL-klo.normalTitle",
        "feature_redeye": "96D-hc-Y9c.normalTitle",
        "feature_canvas": "C0M-D1-UGD.normalTitle",
        "feature_reshape_title": "NOt-6G-UXf.text",
        "feature_whiten_title": "Fo8-wS-7I7.text",
        "feature_details_title": "bUz-UN-PHh.text",
        "feature_smooth_title": "QiC-yZ-uYn.text",
        "feature_defocus_title": "QiC-yZ-uYn.text",
        "feature_patch_title": "85k-Xe-lZ5.text",
        "feature_frames_title": "Phw-WM-nDx.text",
        "feature_tones_title": "Rta-z1-P6x.text",
        "feature_filters_title": "Phw-WM-nDx.text",
        "feature_redeye_title": "mNQ-Ld-eXx.text",
        "feature_canvas_title": "8wZ-ad-wtB.text",
        "action_import_camera": "CAMERA",
        "action_import_gallery": "OPEN PHOTO",
        "action_import_close": "CLOSE THIS PHOTO",
        "action_import_reload": "RELOAD THIS PHOTO",
        "import_camera_missing": "Cannot find any available camera for photo capture.",
        "import_gallery_missing": None,
        "import_email_missing": None,
        "action_share_facebook": "SHARE TO FACEBOOK",
        "action_share_flickr": "SHARE TO FLICKR",
        "action_share_google": None,
        "action_share_instagram": None,
        "action_share_mail": "SEND VIA E-MAIL",
        "action_share_tumblr": "SHARE TO TUMBLR",
        "action_share_twitter": "SHARE TO TWITTER",
        "action_share_other": None,
        "action_share_save": None,
        "share_mail_subject": "LTEXPORT_MAIL_SUBJECT",
        "share_mail_body": "LTEXPORT_MAIL_BODY",
        "share_failed": None,
        "share_using": None,
        "action_overflow_feedback": None,
        "action_overflow_tutorials": "NOTIFICATIONS",
        "action_overflow_rate": "RATE FACETUNE",
        "action_overflow_like": "LIKE US",
        "action_overflow_settings": None,
        "action_apply": None,
        "action_cancel": "Cancel",
        "help_button": "AUV-Ar-8Ze.normalTitle",
        "move_button": "jEF-el-5Zb.normalTitle",
        "erase_button": "iTm-k9-QjI.normalTitle",
        "apply_button": None,
        "flip_button": "NjD-We-N7W.normalTitle",
        "palette_button": "EYF-Lu-wI0.normalTitle",
        "crop_button": "nke-8X-ONa.normalTitle",
        "fixed_button": "X1g-eu-dhm.normalTitle",
        "rotate_button": "prd-Ni-Lp8.normalTitle",
        "crop_fixed_1_1": None,
        "crop_fixed_4_3": None,
        "crop_fixed_3_2": None,
        "crop_fixed_16_10": None,
        "crop_fixed_16_9": None,
        "crop_fixed_2_35_1": None,
        "whiten_button": "Fo8-wS-7I7.text",
        "smooth_button": "0uj-F4-HAK.normalTitle",
        "smoother_button": "zLk-3j-3BI.normalTitle",
        "details_button": "ee0-Uj-HHE.normalTitle",
        "reshape_button": "a7N-OV-cyL.normalTitle",
        "refine_button": "drh-2t-eVI.normalTitle",
        "patch_button": "url-pK-mZh.normalTitle",
        "tones_button": "KK5-ld-dhI.normalTitle",
        "picker_button": "Flr-s8-RKg.normalTitle",
        "redeye_button": "ELX-Iq-bRr.normalTitle",
        "whiteeye_button": "f4G-pM-Rge.normalTitle",
        "defocus_button": "0uj-F4-HAK.normalTitle",
        "blur_button": "8mF-o0-I1i.normalTitle",
        "paper_button": "NJE-00-aRH.normalTitle",
        "lighting_button": "ogB-wa-H3k.normalTitle",
        "texture_button": "ekH-2F-0H8.normalTitle",
        "lens_button": "shz-92-nim.normalTitle",
        "wipe_button": "L4L-50-60H.normalTitle",
        "wipe_tool_button": "hN8-Zj-Wwh.normalTitle",
        "apply_tool_button": "P2F-7B-fgz.normalTitle",
        "fill_tool_button": "1Ip-cC-c0C.normalTitle",
        "clear_tool_button": "6BH-oQ-4IW.normalTitle",
        "filters_confirm_ok": "Apply New Lens",
        "filters_confirm_cancel": "Cancel",
        "filters_confirm_text": "To change the lens effect, local editing mask will be reset.",
        "classic_button": "NJE-00-aRH.normalTitle",
        "artistic_button": "ZVz-Od-a6V.normalTitle",
        "compare_button": "ogB-wa-H3k.normalTitle",
        "select_photo_button": "Select Image",
        "demo_photo_button": "Try a demo photo",
        "import_photo_hint": "qUe-Xh-lkZ.text",
        "help_drag_to_move": "1ub-h3-yn3.text",
        "help_pinch_to_zoom": "4xI-Mq-hsS.text",
        "help_double_tap_to_zoom": "A7y-5Y-Na0.text",
        "help_drag": "R1n-pl-xYW.text",
        "help_crop": "zgB-dd-aWp.text",
        "help_rotate": "g7L-AH-UBL.text",
        "help_flip": "pEh-jb-Zjw.text",
        "help_zoom": "FmU-JU-XtX.text",
        "help_swipe": "T9r-we-7rr.text",
        "help_result": "zfA-fU-Uel.text",
        "help_choose_category": "wsc-V3-Bvh.text",
        "help_pick_filter": "47N-CQ-jUf.text",
        "help_swipe_to_adjust_filter": "E53-7z-EvP.text",
        "help_tap_to_apply_filter": None,
        "help_for_local_filtering_use": "9sK-IS-7ZC.text",
        "help_wipe": "mn9-gu-Js5.text",
        "help_apply": "g0l-w4-98C.text",
        "help_pick_a_frame": "odS-dG-1BD.text",
        "help_create_before_after_picture": "3fb-cL-v9e.text",
        "help_tap_and_drag": "hGm-BJ-zi0.text",
        "help_pinch_to_change_size": "V0f-lx-JBu.text",
        "help_rotate_to_match_texture": "CmZ-po-ODI.text",
        "help_tap": "jhb-tZ-Aoq.text",
        "help_choose_color": "Ush-LP-TI6.text",
        "help_refine": "n5H-fc-80w.text",
        "help_use_refine_for_finer_control": "rhH-uf-39w.text",
        "help_smoother": "gi8-BU-upM.text",
        "help_not_smooth_enough_use_smoother": "SUp-JG-bkT.text",
        "help_long_press_to_select_color": "kH6-FD-Hab.text",
        "help_use_color_utility": "xLB-6m-JIR.text",
        "help_or": "QfI-he-PRI.text",
        "help_change_color_of_objects": "P4w-zG-dmX.text",
        "help_apply_make_up": "YGP-ME-qnA.text",
        "help_tap_to_apply_fix": None,
        "help_drag_and_crop": "ZGe-HP-G3b.text",
        "help_choose_ratio": "hom-Ys-jgj.text",
        "help_tap_to_apply_patch": "nQt-Va-8Pc.text",
        "help_tap_to_flip_patch": "gHJ-ql-zya.text",
        "help_video_error": None,
        "settings_title": None,
        "settings_notifications": None,
        "settings_help_screens_reset": None,
        "settings_help_screens_reset_summary": None,
        "settings_help_screens_reset_ack": None,
        "settings_version": None,
        "settings_licenses": None,
        "tutorials_title": "ksC-X7-RHW.title",
        "tutorials_empty": None,
        "tutorials_error": None,
        "tip_slow_painting": "Tip: for a stronger effect,\nmove your finger slowly",
        "tip_long_press_in_tones": "Tip: long-press to pick\ncolor from your photo",
        "tip_sharing": "Tip: share directly\nfrom Facetune!",
        "tip_compare_button": "Tip: tap and hold\nto view the original",
        "tip_patch_rotation": "Tip: try to rotate the circles\nto find the best match.",
        "tip_two_finger_navigation": "Tip: two fingers to move,\none finger to brush",
        "tip_eraser": "Tip: use eraser where\nthe effect is too strong",
        "tip_zoom_for_control": "Tip: zoom in for better\ncontrol over the result",
        "tip_zoom_for_reshape": "Tip: zoom with two fingers\nto reshape smaller regions",
        "tip_undo_redo": "Tip: undo or redo\nyour recent changes",
        "image_too_small_message": "Facetune works best with images larger than 0.5 megapixels. For best results, open a larger image.",
        "image_too_small_title": "Small Image",
        "load_anyway": "Load Anyway",
        "no_more_undo": "No undo history. Reload original image? This cannot be undone.",
        "reload_original": "Reload Original",
        "image_too_large_message": "The image is larger than the recommended size for your device. Using maximal size will reduce Facetune's stability.",
        "image_too_large_title": "Very Large Image",
        "use_recommended_size": "Use Recommended Size",
        "use_maximum_size": "Use Maximum Size",
        "unsaved_changes_warning": None,
        "unsaved_changes_warning_title": None,
        "open_anyway": None
    }
