name: 'Build APK/Bundle in release mode'
description: >
  The purpose of this action is a safe environment for executing your gradle tasks.
  The tasks:
    1) Cleans the environment using `./gradlew clean` before the compilation.
    2) Executes your specific build commands.

inputs:
  technical-version:
    required: true
    description: The technical version of the build.

  build-commands:
    required: true
    description: >
      The build commands to execute, for example:
      <code>
      ./gradlew :pixaloop:assembleRelease
      </code>

runs:
  using: "composite"
  steps:
    - name: "Set TECHNICAL VERSION"
      shell: bash
      run: echo ::set-env name=TECHNICAL_VERSION::${{inputs.technical-version}}

    - name: "Clean environment"
      shell: bash
      run: ./gradlew clean

    - name: "Execute build commands"
      run: ${{inputs.build-commands}}
      shell: bash
