# Copyright (c) 2021 Lightricks. All rights reserved.
# Created by Ouriel Moses.

name: FeedPlayground App Distribution
env:
  KEY: release
  KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
  KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
  ABI_FILTERS_OVERRIDE: armeabi-v7a:arm64-v8a
on:
  workflow_dispatch:
    inputs:

      firebaseAppDistributionGroups:
        description: >
          The tester groups you want to distribute builds to (see Manage testers in Firebase Console).
          Groups are specified using group aliases, which you can find in the Testers tab in the
          Firebase App Distribution console. You can specify the groups as a comma-separated list of group aliases.
        required: false
        default: 'dev-team'

      firebaseAppDistributionReleaseNotes:
        description: Release notes for this build.
        required: false
        default: ''

jobs:
  test:
    name: "FeedPlayground App tests"
    runs-on: android
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}

      - name: Setup emulator
        uses: ./.github/actions/action-emulator

      - name: "Run tests"
        id: app_test
        uses: ./.github/actions/action-app-tests
        with:
          app: feedplayground

  distribution:
    name: "FeedPlayground for Android release builds"
    needs: test
    runs-on: android
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}

      - name: "Set technical version"
        id: technical_version
        uses: ./.github/actions/action-set-technical-version

      - name: "Set KeyStore"
        uses: ./.github/actions/action-create-keystore
        with:
          base64-keystore: ${{secrets.FACETUNE_KEYSTORE_BASE64}}

      - name: "Build binaries in Release mode"
        uses: ./.github/actions/action-build-release
        with:
          technical-version: ${{ steps.technical_version.outputs.techinal-version }}
          app: feedplayground

      - name: "Upload to FirebaseDistribution"
        uses: ./.github/actions/action-firebase-upload
        with:
          app: feedplayground
          firebase-secret: ${{secrets.FEEDPLAYGROUND_FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT}}
          firebase-app-distribution-groups: ${{github.event.inputs.firebaseAppDistributionGroups}}
          firebase-app-distribution-release-notes: ${{github.event.inputs.firebaseAppDistributionReleaseNotes}}

      - name: "Cleanup"
        if: ${{always()}}
        run: rm ${{env.KEYSTORE}}
