name: Manual Creation of runner instances
on:
  workflow_dispatch:
    inputs:
      instance_num:
        description: Number of instances we want to add
        required: true
        default: 2
      delete_old:
        description: If we want to delete all old instances. Can be either yes or no
        required: true
        default: no

jobs:
  create_runner:
    runs-on: ubuntu-latest
    name: Create Android runner
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Run instance creation
        uses: Lightricks/facetune-android/.github/actions/action-create-gcp-runner@develop
        with:
          instance_num: ${{github.event.inputs.instance_num}}
          delete_old: ${{github.event.inputs.delete_old}}
          gcp_instance_creator_key: ${{secrets.GCP_ANDROID_CI_INSTANCE_CREATOR}}
