name: Nightly build
on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  bundle_release:
    name: "Bundle Release of all apps on develop "
    runs-on: android
    if: (github.event_name == 'schedule' && github.repository == 'Lightricks/facetune-android')
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}
          ref: develop
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle Bundle Release
        run: ./gradlew bundleRelease
      - name: Post failure to slack
        if: ${{ failure() }}
        uses: Lightricks/facetune-android/.github/actions/action-slack@develop
        with:
          text: Nightly failed. Please check https://github.com/Lightricks/facetune-android/actions/runs/${{github.run_id}}
          webhook: ${{secrets.CI_NOTIFICATION_WEBHOOK}}
  run_tests:
    name: "Run all tests including the large ones"
    runs-on: android
    if: (github.event_name == 'schedule' && github.repository == 'Lightricks/facetune-android')
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}
          ref: develop
      # Every container gets a different value for EMULATOR_PORT variable, so they do not collide
      - name: Setup emulator
        uses: Lightricks/facetune-android/.github/actions/action-emulator@develop
      - name: Tests including large test
        run: ./gradlew buildForPR
      - name: Run all python unit tests
        run: python3 -m unittest discover -s tools/jenkins
      - name: Print adb logcat on failure
        if: ${{ failure() }}
        run: adb logcat -d
      - name: Post failure to slack
        if: ${{ failure() }}
        uses: Lightricks/facetune-android/.github/actions/action-slack@develop
        with:
          text: Nightly failed. Please check https://github.com/Lightricks/facetune-android/actions/runs/${{github.run_id}}
          webhook: ${{secrets.CI_NOTIFICATION_WEBHOOK}}
      - name: Upload unit-test logs to GitHub
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: |
            ./**/build/test-results/**/*.xml
            ./**/build/reports/androidTests
            facetune-android/**/build/test-results/**/*.xml
            facetune-android/**/build/reports/androidTests

