name: Nightly build
on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  bundle_release:
    name: "Bundle Release of all apps on develop "
    runs-on: android
    if: (github.event_name == 'schedule' && github.repository == 'Lightricks/facetune-android')
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}
          ref: develop
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle Bundle Release
        run: ./gradlew bundleRelease
