name: Build and test on PR
# This workflow is triggered by webhook when a PR opens / gets updated on 'develop' branch
# it is also triggered on retest
on:
  pull_request:
  issue_comment:
    types: [created]

env:
  ABI_FILTERS_OVERRIDE: x86
  # Environment variable for the repo name, in the format 'Lightricks/Repo'.
  ghprbGhRepository: ${{ github.repository }}
  # Environment variable for the pull request ID.
  ghprbPullId: ${{ github.event.number }}
  # The EMULATOR_HOST_FOR_CONTAINER environment variable is different for each docker container, as setup by kubernetes

jobs:
  assemble_and_test:
    name: Build and test PR
    if:  github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.comment.body == 'retest')
    # This job runs on our self-hosted linux runners, labeled 'android'
    runs-on: android
    steps:
      # this plugin cancels previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          # To access submodules in Lightricks repo, we need a personal access token
          token: ${{ secrets.GITHUBCIPAT }}

      - name: Apply GitHub labels
        env:
          # Environment variable holding the Github username.
          DANGER_GITHUB_API_USER: ${{ secrets.GITHUBCIUSER }}
          # Environment variable holding the Github password.
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUBCIPAT }}
        run: |
          mkdir -p "build-logs"
          (python3 tools/jenkins/ApplyGithubLabels.py || echo "failed reporting status to github") | tee -a "build-logs/output.log"

      # TODO: Add emulator deletion
      # Every container gets a different value for EMULATOR_PORT variable, so they do not collide
      - name: Setup emulator
        id: setup_emulator
        run: |
          set -x
          # Setup new avd every time with --force
          echo no | avdmanager create avd -n android28 -k "system-images;android-28;default;x86" --force
          emulator -list-avds
          emulator -gpu swiftshader_indirect -no-window -feature GLESDynamicVersion -avd android28 -memory 2048 -partition-size 2048 -cache-size 2048 >/dev/null 2>&1 &

          # bootanim=""
          # timeout_in_seconds=60
          # failcounter=-1

          # while true; do
          #    bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
          #    let "failcounter += 1"
          #    sleep 1

          #    if [[ failcounter -gt timeout_in_seconds ]]; then
          #        echo "Timeout ($timeout_in_seconds seconds) reached; failed to start emulator"
          #        exit 1
          #    fi

          #    if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
          #        || "$bootanim" =~ "running" || "$bootanim" =~ "no emulators found" ]]; then
          #        echo "Waiting for emulator to start. failed $failcounter times"
          #        continue
          #    elif [[ "$bootanim" =~ "stopped" ]]; then
          #        echo "Emulator is ready"
          #        break
          #    else
          #        echo "Error booting emulator"
          #        echo "$bootanim"
          #        exit 1
          #    fi
          #done

      - name: Gradle clean
        run: ./gradlew clean

      - name: Build and test modified modules with gradle
        timeout-minutes: 35
        env:
          # Environment variable holding the Github username.
          DANGER_GITHUB_API_USER: ${{ secrets.GITHUBCIUSER }}
          # Environment variable holding the Github password.
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUBCIPAT }}
        # Note that this will run tests only on the emulator device defined by the ANDROID_SERIAL variable
        run: python3 ./tools/jenkins/build_modified_modules_v2.py

      - name: Print adb logcat on failure
        timeout-minutes: 1
        if: ${{ failure() }}
        run: adb logcat -d
      - name: Post test results on GitHub
        if: ${{ failure() || success() }}
        env:
          # Environment variable holding the Github username.
          DANGER_GITHUB_API_USER: ${{ secrets.GITHUBCIUSER }}
          # Environment variable holding the Github password.
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUBCIPAT }}
        run: python3 tools/jenkins/ReportBuildStatus.py "$GITHUB_WORKSPACE" || echo "failed reporting status to github"

      - name: Upload unit-test logs to GitHub
        if: ${{ failure() || success() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: |
            ./**/build/test-results/**/*.xml
            ./**/build/reports/androidTests
            facetune-android/**/build/test-results/**/*.xml
            facetune-android/**/build/reports/androidTests

      - name: Kill emulator
        if: ${{ always() }}
        run: |
          #TODO: Make terminate_emulators.py use adb from PATH, delete env varaible "ADB_HOME"
          export ADB_HOME=$ANDROID_HOME/platform-tools
          python3 tools/jenkins/terminate_emulators.py
